trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '.. -G "Visual Studio 16 2019" -A x86'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '--build . --config Release'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build/bin_dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/libplctag_windows_x86_$(Build.BuildId).zip'
    replaceExistingArchive: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/src/lib/libplctag.h'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/libplctag_windows_x86_$(Build.BuildId).zip'
    replaceExistingArchive: false


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/libplctag_windows_x86_$(Build.BuildId).zip'
    artifactName: libplctag_windows_x86_$(Build.BuildId)