name: Ubuntu CI

on:
  push:
    branches: [ test_actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up build environment
      run: sudo apt install build-essential cmake
    -name: Create build directory
      run: mkdir build; cd build
    -name: Configure CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
    -name: Build
      run: cmake build
    -name: Test
      run: echo "no-op for now"
    -name: Package library binaries.
      run: cd bin_dist; zip ubuntu_x64_${build_id}_lib.zip libplctag.so*
    -name: Package development files
      run: zip ubuntu_x64_${build_id}_dev.zip libplctag.h libplctag.pc 
    -name: Package tools
      run: zip ubuntu_x64_${build_id}_tools.zip list_tags tag_rw

